import type { Metadata } from "next";
import StepProvider from "@/store/steps";

export const metadata: Metadata = {
  title: "Digital Accessibility Game",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
	params,
}: Readonly<{
  children: React.ReactNode;
	params: Promise<{ stepId: string }>;
}>) {
	const { stepId } = await params;

  return (
    <StepProvider stepId={stepId}>
      {children}
    </StepProvider>
  );
}
