import type { Metadata } from "next";
import GameProvider from "@/store/game";

export const metadata: Metadata = {
  title: "Digital Accessibility Game",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
	params,
}: Readonly<{
  children: React.ReactNode;
	params: Promise<{ gameId: string }>;
}>) {
	const { gameId } = await params;

  return (
    <GameProvider gameId={gameId}>
      {children}
    </GameProvider>
  );
}
